// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9pI-e5SlC5vzCThyU6jwti4kkGwmRME',
    appId: '1:768639171487:web:b88dd342e8f3d4fc789baa',
    messagingSenderId: '768639171487',
    projectId: 'flow-58d44',
    authDomain: 'flow-58d44.firebaseapp.com',
    storageBucket: 'flow-58d44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgNM26J5itv6uqKKmZ2ntxML0TGV83lZ4',
    appId: '1:768639171487:android:f5dec791b8e3ebc0789baa',
    messagingSenderId: '768639171487',
    projectId: 'flow-58d44',
    storageBucket: 'flow-58d44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6pYog26Ukjc5b3aDfYaE9AOoxB6bFGcc',
    appId: '1:768639171487:ios:8ea04a69ce1bb73c789baa',
    messagingSenderId: '768639171487',
    projectId: 'flow-58d44',
    storageBucket: 'flow-58d44.firebasestorage.app',
    iosBundleId: 'com.example.flow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6pYog26Ukjc5b3aDfYaE9AOoxB6bFGcc',
    appId: '1:768639171487:ios:8ea04a69ce1bb73c789baa',
    messagingSenderId: '768639171487',
    projectId: 'flow-58d44',
    storageBucket: 'flow-58d44.firebasestorage.app',
    iosBundleId: 'com.example.flow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD9pI-e5SlC5vzCThyU6jwti4kkGwmRME',
    appId: '1:768639171487:web:de0792d1748620c1789baa',
    messagingSenderId: '768639171487',
    projectId: 'flow-58d44',
    authDomain: 'flow-58d44.firebaseapp.com',
    storageBucket: 'flow-58d44.firebasestorage.app',
  );
}
